# Generated by Django 4.1.3 on 2023-01-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_alter_user_dark_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='page_size',
            field=models.IntegerField(default=8, verbose_name='Кол-во публикаций на странице'),
        ),
    ]
