# Generated by Django 4.1.3 on 2023-02-12 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0005_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
