# Generated by Django 4.1.3 on 2022-11-11 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='DubWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='Никнэйм')),
                ('page', models.URLField(blank=True, null=True, verbose_name='Ссылка на личную страницу')),
                ('job', models.CharField(choices=[('dubber', 'даббер'), ('sounder', 'технарь'), ('translator', 'переводчик')], max_length=10, verbose_name='Должность')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Работающий над озвучками',
                'verbose_name_plural': 'Работающие над озвучками',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Ссылка')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('page', models.URLField(blank=True, null=True, verbose_name='Ссылка на личную страницу')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Персона',
                'verbose_name_plural': 'Персоны',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Оригинальное название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Ссылка')),
                ('rus_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название на русском')),
                ('lat_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Оригинальное название на латинице')),
                ('description', models.TextField(blank=True, max_length=600, null=True, verbose_name='Описание')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='Постер')),
                ('year', models.CharField(blank=True, max_length=9, null=True, validators=[post.utils.validate_year], verbose_name='Год')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('kinopoisk_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='ID KinoPoisk')),
                ('imdb_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='ID IMDB')),
                ('shikimory_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID Shikimory')),
                ('wa_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='ID World-Art')),
                ('mdl_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='ID MyDoramaList')),
                ('season_total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Всего сезонов')),
                ('season', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вышло сезонов')),
                ('episode_total', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Всего серий')),
                ('episode', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вышло серий')),
                ('category', models.ManyToManyField(blank=True, to='post.category', verbose_name='Категория')),
                ('dub_workers', models.ManyToManyField(blank=True, to='post.dubworker', verbose_name='Люди работающие над озвучкой')),
                ('genre', models.ManyToManyField(blank=True, to='post.genre', verbose_name='Жанр')),
                ('persons', models.ManyToManyField(blank=True, to='post.person', verbose_name='Люди работающие над этим')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zcdn_id', models.PositiveIntegerField(verbose_name='ID файла на ZeroCDN')),
                ('episode_num', models.PositiveSmallIntegerField(default=1, verbose_name='Номер серии')),
                ('season_num', models.PositiveSmallIntegerField(default=1, verbose_name='Номер сезона')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400, verbose_name='Текст')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
