# Generated by Django 4.1.3 on 2022-11-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='shikimory_id',
            new_name='shikimori_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='wa_id',
            new_name='wa_link',
        ),
    ]
