# Generated by Django 4.1.3 on 2022-11-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_shikimory_id_post_shikimori_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='wa_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на World-Art'),
        ),
    ]
