# Generated by Django 4.1.3 on 2022-12-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_wa_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
