# Generated by Django 4.1.3 on 2022-12-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0004_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dubworker',
            name='nickname',
        ),
        migrations.AddField(
            model_name='dubworker',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dubworker',
            name='job',
            field=models.CharField(choices=[('dubber', 'даббер'), ('sounder', 'технарь'), ('translator', 'переводчик'),
                                            ('team', 'команда')], max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='dubworker',
            name='page',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на страницу'),
        ),
    ]
