# Generated by Django 4.1.3 on 2023-01-06 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0007_rename_title_orig_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='title_orig',
        ),
    ]
