# Generated by Django 4.1.3 on 2023-01-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0008_rename_title_post_title_orig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=1200, null=True, verbose_name='Описание'),
        ),
    ]
