# Generated by Django 4.1.3 on 2023-01-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0009_alter_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
