# Generated by Django 4.1.3 on 2023-01-15 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0012_post_vote_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vote_count',
        ),
        migrations.AddField(
            model_name='post',
            name='voted',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Кол-во проголосовавших'),
        ),
    ]
