# Generated by Django 4.1.3 on 2023-02-12 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('post', '0013_remove_post_vote_count_post_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='voted',
        ),
    ]
