# Generated by Django 4.1.3 on 2023-01-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_page', models.CharField(max_length=100, verbose_name='Следующая страница')),
                ('page', models.CharField(max_length=100, verbose_name='Последняя спаршенная страница')),
            ],
        ),
    ]
