# Generated by Django 4.1.3 on 2023-01-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kodik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsed',
            name='all_have',
            field=models.BooleanField(default=False, verbose_name='Все с этой стр. уже добавленны'),
        ),
    ]
