# Generated by Django 4.1.3 on 2023-01-06 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('order_table', '0002_rename_orig_title_order_title_orig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
