# Generated by Django 4.1.3 on 2022-12-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('video', '0002_alter_video_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ftp_url',
            field=models.URLField(blank=True, help_text='начинающийся с /', null=True, verbose_name='URL на FTP'),
        ),
    ]
