# Generated by Django 4.1.3 on 2022-12-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('video', '0003_video_ftp_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='ftp_url',
            field=models.CharField(blank=True, help_text='начинающийся с /', max_length=200, null=True,
                                   verbose_name='URL на FTP'),
        ),
    ]
