# Generated by Django 4.1.3 on 2023-01-05 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('video', '0004_alter_video_ftp_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='ftp_url',
        ),
    ]
