# Generated by Django 4.1.3 on 2023-01-05 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('video', '0005_remove_video_ftp_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='bunny_id',
            new_name='file_url',
        ),
    ]
