# Generated by Django 4.1.3 on 2023-01-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('video', '0006_rename_bunny_id_video_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='translate',
            field=models.CharField(default='Неизвестный', max_length=100, null=True, verbose_name='Перевод'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_url',
            field=models.CharField(max_length=100, verbose_name='URL видео'),
        ),
    ]
